# User input configuration for JWST photometry script

source_detection:
  kernel: 3.5  # pixel FWHM Gaussian
  minarea: 3  # pixels
  thresh: 1.2  # Ïƒ
  deblend_nthresh: 32
  deblend_cont: 0.0001
  clean: N

psf_homogenization:
  target_psf: F444W
  regularization_parameter: 0.003  # for Pypher

aperture_photometry:
  apertures: [0.32, 0.48, 0.70, 1.00, 1.40]  # diameter in arcseconds
  elliptical_kron_factor: 2.5
  min_kron_factor: 1.0

photometric_corrections:
  f444w_curve_of_growth: true
  local_noise_box_size: 9  # pixels
  num_background_apertures: 10000
  outlier_sigma: 5
  use_circle_flag: true

output:
  catalog_format: fits
  output_directory: ./output

images:
  F115W: data/F115W.fits
  F115W_weight: data/F115W_weight.fits
  F150W: data/F150W.fits
  F150W_weight: data/F150W_weight.fits
  F200W: data/F200W.fits
  F200W_weight: data/F200W_weight.fits
  F277W: data/F277W.fits
  F277W_weight: data/F277W_weight.fits
  F356W: data/F356W.fits
  F356W_weight: data/F356W_weight.fits
  F410M: data/F410M.fits
  F410M_weight: data/F410M_weight.fits
  F444W: data/F444W.fits
  F444W_weight: data/F444W_weight.fits
